spec:
#  replicas: "5"
  template:
    spec:
      containers:
        - 
          resources:
            requests:
 #             cpu: "0.2"
 #             memory: 64M
            limits:
 #             cpu: "2.0"
 #             memory: 256M
